import Head from "next/head";
import React from "react";
import Script from "next/script";
import Grid from "@mui/material/Grid";

export default function Chatbot() {
  return (
    <>
      <Head>
        <title>The World Of Joy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
          async
        />
        <link
          href="https://propstory.in/universe-chat-bot-html-template/css/worldofjoy-chatbot.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>
      <Grid
        container
        style={{
          margin: 0,
          height: "100vh",
          position: "relative",
          background: "#24bbdc",
        }}
      >
        <div className="chat-bot-icon" />
        <Script
          src="https://propstory.in/universe-chat-bot-html-template/js/WorldofJoy-chatbotNew.js"
          async
        />
      </Grid>
    </>
  );
}
