import Head from "next/head";
import React from "react";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import Script from "next/script";

export default function ChatBot() {
  return (
    <>
      <Head>
        <title>The World Of Joy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
        <link
          href="https://propstory.in/universe-chat-bot-html-template/css/worldofjoy-chatbot.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>
      <Grid
        container
        style={{
          margin: 0,
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          background: "#24bbdc",
        }}
      >
        <Box component="div" className="chat-bot-icon" />
        <Script
          src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"
          async
        />
        <Script
          src="https://propstory.in/universe-chat-bot-html-template/js/WorldofJoychatbot_cloned.js"
          async
        />
      </Grid>
    </>
  );
}
